import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google'
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { headers } from 'next/headers';
import { getUserId } from "@/utils/analytics";
import PageViewTracker from "@/components/PageViewTracker";


const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const userAgent = headersList.get('user-agent') || '';

  return (
    <html lang="en" className={ibmPlexSans.className}>
      <body>
        <div className="hidden md:block">
          <Navbar />
        </div>
        <PageViewTracker userAgent={userAgent} />
        {children}
        <Footer />
      </body>
    </html >
  );
}
