import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google'
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ibmPlexSans.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html >
  );
}
